# permissions for end users to edit operatormanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: operatormanager-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kom
    app.kubernetes.io/part-of: kom
    app.kubernetes.io/managed-by: kustomize
  name: operatormanager-editor-role
rules:
- apiGroups:
  - kom.kkb.jp
  resources:
  - operatormanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kom.kkb.jp
  resources:
  - operatormanagers/status
  verbs:
  - get
