---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kom.kkb.jp
  resources:
  - operatormanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kom.kkb.jp
  resources:
  - operatormanagers/finalizers
  verbs:
  - update
- apiGroups:
  - kom.kkb.jp
  resources:
  - operatormanagers/status
  verbs:
  - get
  - patch
  - update
