apiVersion: kom.kkb.jp/v1alpha1
kind: OperatorManager
metadata:
  name: kom
  namespace: kom-system
spec:
  cleanup: true
  resource:
    helm:
      - name: repo1
        url: https://helm.github.io/examples
        charts:
          - name: hello-world
            version: x.x.x
