apiVersion: kom.kkb0318.github.io/v1alpha1
kind: OperatorManager
metadata:
  name: kom
  namespace: kom-system
spec:
  tool: flux
  cleanup: true
  resource:
    helm:
      - name: jetstack
        url: https://charts.jetstack.io
        charts:
          - name: cert-manager
            version: v1.14.4
            values:
              installCRDs: true
              prometheus:
                enabled: false
      - name: repo1
        url: https://helm.github.io/examples
        charts:
          - name: hello-world
            version: x.x.x
    git:
      - name: "gitrepo1"
        url: "https://github.com/operator-framework/operator-sdk"
        path: "testdata/helm/memcached-operator/config/default"
        reference:
          type: tag # tag or branch or semver
          value: "v1.33.0"
