apiVersion: kom.kkb.jp/v1alpha1
kind: OperatorManager
metadata:
  name: kom
  namespace: kom-system
spec:
  tool: argo
  cleanup: true
  resource:
    git:
      - name: "gitrepo1"
        url: "https://github.com/operator-framework/operator-sdk"
        path: "testdata/helm/memcached-operator/config/default"
        reference:
          values: "v1.33.0"
