apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kom.fullname" . }}-manager-role
  labels:
  {{- include "kom.labels" . | nindent 4 }}
rules:
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kom.kkb.jp
  resources:
  - operatormanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kom.kkb.jp
  resources:
  - operatormanagers/finalizers
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - kom.kkb.jp
  resources:
  - operatormanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kom.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kom
    app.kubernetes.io/part-of: kom
  {{- include "kom.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kom.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kom.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'