apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kom.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kom
    app.kubernetes.io/part-of: kom
  {{- include "kom.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}